# Generated by Django 5.2.7 on 2025-11-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start_time', models.TimeField(blank=True, help_text='Preferred shift start time (e.g., 08:00)', null=True)),
                ('preferred_end_time', models.TimeField(blank=True, help_text='Preferred shift end time (e.g., 16:00)', null=True)),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text='List of preferred days: ["monday", "tuesday", ...]')),
                ('max_hours_per_week', models.IntegerField(default=40, help_text='Maximum hours this PA can work per week')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this PA (admin only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PA'}, on_delete=django.db.models.deletion.CASCADE, related_name='pa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PA Profile',
                'verbose_name_plural': 'PA Profiles',
                'db_table': 'pa_profiles',
            },
        ),
        migrations.CreateModel(
            name='PAScheduleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shifts_worked', models.IntegerField(default=0)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_hours_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('most_common_days', models.JSONField(blank=True, default=dict, help_text='{"monday": 15, "wednesday": 12, ...}')),
                ('most_common_start_time', models.TimeField(blank=True, null=True)),
                ('most_common_shift_length', models.DecimalField(blank=True, decimal_places=2, help_text='Average shift duration in hours', max_digits=4, null=True)),
                ('preferred_shift_pattern', models.CharField(blank=True, choices=[('morning', 'Morning (6-9 AM)'), ('evening', 'Evening (9-10 PM)'), ('full_day', 'Full Day'), ('mixed', 'Mixed')], max_length=20)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of completed shifts without cancellation (0-100)', max_digits=5)),
                ('typical_request_timing', models.IntegerField(blank=True, help_text='Average days before shift date that PA typically requests', null=True)),
                ('consecutive_days_preference', models.IntegerField(blank=True, help_text='Average number of consecutive days worked', null=True)),
                ('last_worked_date', models.DateField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('pa', models.OneToOneField(limit_choices_to={'role': 'PA'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PA Schedule Statistics',
                'verbose_name_plural': 'PA Schedule Statistics',
                'db_table': 'pa_schedule_stats',
            },
        ),
    ]
