# Generated by Django 5.2.7 on 2025-11-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paprofile_paschedulestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('both', 'Email and SMS'), ('email', 'Email only'), ('sms', 'SMS only'), ('none', 'None')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
