# Generated by Django 5.2.7 on 2025-11-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shiftsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
